### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by kdungs** [fstate/fstate#10]
It would be pretty awesome, if the particle names and arrows would be rendered using unicode (say UTF-8).

For example `→` instead of `-->` and `J/ψ` instead of `J/psi`.

Of course this shouldn't affect the ability to search for particles by the old strings.

**Comment by mozgit** [comment]
Good point. We either can do like PDG (i.e. use some kind of LaTeX rendering, or whatever do they use) which is complicated or we can simply replace particles by UTF-8 codes during the rendering. 
The PDG way will require attach at LaTeX code to every particle (which should be done by hands, I afraid)
The 'simple' way will miss underline/upperline indecies (all these _2 and ^0)

**Comment by kdungs** [comment]
Ideally, one would also replace those. E.g. https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts

Something like `x²` instead of `x^2`.

**Comment by mozgit** [comment]
Also we have bars and often upper indices are not indicated as such:
K_1(1270)~0
Xi*_cc~--
But probably there should be some smart way to parse these names...

**Comment by mozgit** [comment]
Added MathJax support.
